CREATE OR ALTER PROCEDURE [System].[DeleteEntity]
	@EntityId int
AS
BEGIN
	SET NOCOUNT ON
	SET XACT_ABORT ON
	BEGIN TRY
		BEGIN TRANSACTION
			DELETE FROM [Mud].[Entity] WHERE [EntityId]=@EntityId
		COMMIT
		RETURN 0
	END TRY
	BEGIN CATCH
		ROLLBACK
		RETURN -1
	END CATCH	
END